DROP TABLE RECIPEDIARY CASCADE CONSTRAINT;
CREATE TABLE RECIPEDIARY
(
 	ID 				VARCHAR2(100)     	NOT NULL ,
	NAME 			VARCHAR2(500)   	NOT NULL ,
	INGREDIENTID 	VARCHAR2(100),
	RECIPEID 		VARCHAR2(100),
	FILEID 			VARCHAR2(100),
	DESCRIPTION 	VARCHAR2(4000),
	CREATEDAT    	DATE(),
	MODIFIEDAT    	DATE(),
	VIEWCOUNT		NUMBER
)
TABLESPACE TBSGOMHOME;

CREATE INDEX iRECIPEDIARY_ID_ ON RECIPEDIARY
(
	ID  ASC
)
TABLESPACE TBSGOMHOMEINDEX;