DROP TABLE BASETEST CASCADE CONSTRAINT;
CREATE TABLE BASETEST
(
 	ID_ VARCHAR2(20)     NOT NULL ,
	PRODUCT VARCHAR2(200)     ,
	PNUM VARCHAR2(1000)
)
TABLESPACE TBSGOMHOME;

CREATE INDEX iBASETEST_ID_ ON BASETEST
(
	ID_  ASC
)
TABLESPACE TBSGOMHOMEINDEX;